{
  parserClass="org.onj.language.OnjParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Onj"
  psiImplClassSuffix="Impl"
  psiPackage="org.onj.language.psi"
  psiImplPackage="org.onj.language.psi.impl"

  elementTypeHolderClass="org.onj.language.psi.OnjTypes"
  elementTypeClass="org.onj.language.psi.OnjElementType"
  tokenTypeClass="org.onj.language.psi.OnjTokenType"
}

//<digit> ::= 0|1|2|3|4|5|6|7|8|9
//<integer> ::= <digit> | <digit><integer>
//<float> ::= <integer> "." <integer> | "." <integer>


//OnjFile ::= item_*
//
//private item_ ::= (property|COMMENT|CRLF)
//
//property ::= (KEY? SEPARATOR VALUE?) | KEY

// (elem ( ',' elem)*) | WHITE_SPACE | BLOCK_COMMENT | COMMENT

//OnjFile ::= item_*
//
//private item_ ::= <pair> | WHITE_SPACE
//
//
//<any>   ::= "."
//<stringEsc> ::= "\\" <any>
//<MyText>::= ""
//
//namedKeys ::=  '"' *(<stringEsc> | <any>) '"' | "'" *(<any>) "'" | <MyText>
//
//
//<elem> ::= WHITE_SPACE (<array> | <object> |   elem | <pair> | <primitive>)
//
//
//<primitive> ::= <bool> | <integer> | <float> | <MyText> | "null"
//<bool> ::= "true" | "false"
//<digit> ::= 0|1|2|3|4|5|6|7|8|9
//<integer> ::= <digit> | <digit><integer>
//<float> ::= <integer> "." <integer> | "." <integer>
//<pair> ::= namedKeys SEPARATOR <elem>
//
//
//<array> ::= '[' ( <elem> ( ',' <elem>)* | ) ']'
//<object> ::= '[' ( <pair> ( ',' <pair>)* | ) ']'

//var x="darkmode"

//0x 0o 0b    hex, oct, binär, nur ganzzahlig
// rechnungen bei import und ...(function()) mit klammer, sonst ohne
// use abcdefg;
// function ist teil einer Rechnung
// infix functionen sind shit
//

//abc: 3 rnd()
//import "./shit/"

OnjFile ::= (topLevel)
whi::=WHITE_SPACE?
topLevel::= (((variable | use | import)  topLevel?) | (pair (SEPARATOR topLevel)?) | (whi))
//topLevel::= (variable)

variable ::= "var" whi NAME_CHARACTER whi "=" whi elem_no_pair whi SEMIQOLON
use ::= "use" whi NAME_CHARACTER whi SEMIQOLON
import ::= "import" whi STRING_VALUE whi "as" whi NAME_CHARACTER whi SEMIQOLON

//private item_ ::= (whi elem whi (((SEPARATOR item_))|(SEPARATOR?)))
//elem ::= ( primitive | pair| STRING_VALUE | array | object) whi

private item_no_pair_ ::= (whi elem_no_pair whi)

pair ::=  whi (NAME_CHARACTER | STRING_VALUE) whi ASSIGN whi item_no_pair_

elem_no_pair ::= ( primitive | STRING_VALUE | array | object) whi

primitive ::= whi (bool | float | integer | "null")
bool ::= ("true"|"false")
digit ::= ("0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9")
integer ::= (digit "_"* integer|(digit))
float ::= ((integer "." integer) | ("." integer))
array ::= '['  whi ( item_no_pair_ whi  (((SEPARATOR item_no_pair_)+)|(SEPARATOR?)))?  whi ']'
object ::= '{'  whi ( pair whi (((SEPARATOR pair)+)|(SEPARATOR?)) )?  whi '}'